/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Grafo;
import Storage.GraphSession;

/**
 *
 * @author lukin
 */
public class frmMatrizIncidencia extends javax.swing.JFrame {

    /**
     * Creates new form frmMatrizIncidencia
     */
    Grafo grafo = new Grafo();

    public frmMatrizIncidencia() {
        initComponents();
        this.grafo = GraphSession.getGrafo();

        int indice = 0;
        Grafo g = grafo;
        int[][] v = grafo.matrizIncidencia(g);
        for (int i = 0; i <= (g.getArestas().size() - 1); i++) {
            if (indice == 0) {
                jtaMatrizIncidencia.append("     ");
                indice = 1;
                jtaMatrizIncidencia.append("  " + g.getArestas().get(i).getNomeAresta());
            } else {
                jtaMatrizIncidencia.append("  " + g.getArestas().get(i).getNomeAresta());
            }
        }
        for (int j = 0; j <= (g.getVertices().size() - 1); j++) {
            jtaMatrizIncidencia.append("\n");
            jtaMatrizIncidencia.append("  " + g.getVertices().get(j).getId());
            for (int i = 0; i <= (g.getArestas().size() - 1); i++) {
                jtaMatrizIncidencia.append("  " + v[j][i]);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMatrizIncidencia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtaMatrizIncidencia.setEditable(false);
        jtaMatrizIncidencia.setColumns(20);
        jtaMatrizIncidencia.setRows(5);
        jScrollPane1.setViewportView(jtaMatrizIncidencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMatrizIncidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMatrizIncidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMatrizIncidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMatrizIncidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grafo grafo = null;
                new frmMatrizIncidencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaMatrizIncidencia;
    // End of variables declaration//GEN-END:variables
}
